# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `sdp`")
spark.sql("USE SCHEMA `source`")

# COMMAND ----------

display(spark.sql("SELECT * FROM samples.wanderbricks.users"))
